let mentors_27 = [
  { name: "Abhinav Shukla", role: "", image: "https://ik.imagekit.io/mwwyrq9z8/mentors/mentors_photo/abhinav_shukla.jpeg" },
  { name: "Disanti Ghosh", role: "", image: "https://ik.imagekit.io/mwwyrq9z8/mentors/mentors_photo/disanti_ghosh.jpg" },
  { name: "Vinayak Dixit", role: "", image: "https://ik.imagekit.io/mwwyrq9z8/mentors/mentors_photo/vinayak_dixit.jpeg" },
  { name: "Prince Tiwari", role: "", image: "https://ik.imagekit.io/mwwyrq9z8/mentors/mentors_photo/prince_tiwari.jpeg" },
  { name: "Prakriti Aryan", role: "", image: "https://ik.imagekit.io/mwwyrq9z8/mentors/mentors_photo/prakriti_aryan.jpg" },
  { name: "Aditya Agrawal", role: "", image: "https://ik.imagekit.io/mwwyrq9z8/mentors/mentors_photo/aditya_agrawal.jpg" },
  { name: "Somil Gupta", role: "", image: "https://ik.imagekit.io/mwwyrq9z8/mentors/mentors_photo/somil_gupta.jpg" },
  { name: "Akanksha Kumari", role: "", image: "https://ik.imagekit.io/mwwyrq9z8/mentors/mentors_photo/akanksha_kumari.jpg" },
  { name: "Abhijeet Mishra", role: "", image: "https://ik.imagekit.io/mwwyrq9z8/mentors/mentors_photo/abhijeet_mishra.jpg" },
  { name: "Aman Sharma", role: "", image: "https://ik.imagekit.io/mwwyrq9z8/mentors/mentors_photo/aman_sharma.jpg" },
  { name: "Amit Kumar", role: "", image: "https://ik.imagekit.io/mwwyrq9z8/mentors/mentors_photo/amit_kumar.jpg" },
  { name: "Utkarsh Rajput", role: "", image: "https://ik.imagekit.io/mwwyrq9z8/mentors/mentors_photo/utkarsh_rajput.jpg" },
  { name: "Amrit Raj", role: "", image: "https://ik.imagekit.io/mwwyrq9z8/mentors/mentors_photo/amrit_raj.jpg" },
  { name: "Ankit Pandey", role: "", image: "https://ik.imagekit.io/mwwyrq9z8/mentors/mentors_photo/ankit_pandey.jpg" },
  { name: "Ayush Shivam", role: "", image: "https://ik.imagekit.io/mwwyrq9z8/mentors/mentors_photo/ayush_shivam.jpg" },
  { name: "Ayush Tiwari", role: "", image: "https://ik.imagekit.io/mwwyrq9z8/mentors/mentors_photo/ayush_tiwari.jpg" },
  { name: "Bhavika Vishnoi", role: "", image: "https://ik.imagekit.io/mwwyrq9z8/mentors/mentors_photo/bhavika_vishnoi.jpg" },
  { name: "Dhreej Yadav", role: "", image: "https://ik.imagekit.io/mwwyrq9z8/mentors/mentors_photo/dhreej_yadav.jpg" },
  { name: "Gaurav Kumar Saha", role: "", image: "https://ik.imagekit.io/mwwyrq9z8/mentors/mentors_photo/gaurav_kumar_saha.png" },
  { name: "Harsh Kumar", role: "", image: "https://ik.imagekit.io/mwwyrq9z8/mentors/mentors_photo/harsh_kumar.jpg" },
  { name: "Maniranjan", role: "", image: "https://ik.imagekit.io/mwwyrq9z8/mentors/mentors_photo/maniranjan.jpg" },
  { name: "Mukesh Dhadhariya", role: "", image: "https://ik.imagekit.io/mwwyrq9z8/mentors/mentors_photo/mukesh_dhadhariya.jpg" },
  { name: "Nikhil Gupta", role: "", image: "https://ik.imagekit.io/mwwyrq9z8/mentors/mentors_photo/nikhil_gupta.jpg" },
  { name: "Nitin Gupta", role: "", image: "https://ik.imagekit.io/mwwyrq9z8/mentors/mentors_photo/nitin_gupta.jpg" },
  { name: "Parth Tiwari", role: "", image: "https://ik.imagekit.io/mwwyrq9z8/mentors/mentors_photo/parth_tiwari.jpg" },
  { name: "Prakhar Prakash", role: "", image: "https://ik.imagekit.io/mwwyrq9z8/mentors/mentors_photo/prakhar_prakash.jpg" },
  { name: "Raj Kesharwani", role: "", image: "https://ik.imagekit.io/mwwyrq9z8/mentors/mentors_photo/raj_kesharwani.jpg" },
  { name: "Rishab Kumar", role: "", image: "https://ik.imagekit.io/mwwyrq9z8/mentors/mentors_photo/rishab_kumar.jpg" },
  { name: "Samriddhi Tripathi", role: "", image: "https://ik.imagekit.io/mwwyrq9z8/mentors/mentors_photo/samriddhi_tripathi1.jpg" },
  { name: "Sanyam Jain", role: "", image: "https://ik.imagekit.io/mwwyrq9z8/mentors/mentors_photo/sanyam_jain.jpg" },
  { name: "Shikhar Rai", role: "", image: "https://ik.imagekit.io/mwwyrq9z8/mentors/mentors_photo/shikhar_rai.jpg" },
  { name: "Shivanshu Pandey", role: "", image: "https://ik.imagekit.io/mwwyrq9z8/mentors/mentors_photo/shivanshu_pandey.jpeg" },
  { name: "Shivendu Paul", role: "", image: "https://ik.imagekit.io/mwwyrq9z8/mentors/mentors_photo/shivendru_paul.jpg" },
  { name: "Shreyansh Anand", role: "", image: "https://ik.imagekit.io/mwwyrq9z8/mentors/mentors_photo/shreyansh_anand.jpg" },
  { name: "Shreyanshi Srivastava", role: "", image: "https://ik.imagekit.io/mwwyrq9z8/mentors/mentors_photo/shreyanshi_srivastava.jpg" },
  { name: "Nishchay Gupta", role: "", image: "https://ik.imagekit.io/mwwyrq9z8/mentors/mentors_photo/nishchay_gupta.jpg" },
  { name: "Aastik Das", role: "", image: "https://ik.imagekit.io/mwwyrq9z8/mentors/mentors_photo/aastik_das.jpg" },
  { name: "Jyoti Saxena", role: "", image: "https://ik.imagekit.io/mwwyrq9z8/mentors/mentors_photo/jyoti_saxena.jpg" },
  { name: "Parampreet Singh", role: "", image: "https://ik.imagekit.io/mwwyrq9z8/mentors/mentors_photo/parampreet_singh.jpg" },
  { name: "Vaibhav Mishra", role: "", image: "https://ik.imagekit.io/mwwyrq9z8/mentors/mentors_photo/vaibhav_mishra.jpg" },
  { name: "Srishti Priya", role: "", image: "https://ik.imagekit.io/mwwyrq9z8/mentors/mentors_photo/srishti_priya.jpg" },
  { name: "Aman Gupta", role: "", image: "https://ik.imagekit.io/mwwyrq9z8/mentors/mentors_photo/aman_gupta.jpg" },
];

export default mentors_27;
